before_script:
  - pip install tox

image: python:3.4

services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

py34:
  image: python:3.4
  script:
    - tox -e py34

py35:
  image: python:3.5
  script:
    - tox -e py35

py36:
  image: python:3.6
  script:
    - tox -e py36

docs:
  script:
    - tox -e docs

flake8:
  script:
    - tox -e flake8
